### PR TITLE
[WIP] Initial implementation

### PR DESCRIPTION
**Pull request by rutsky**
This is WIP of an initial implementation of the CORS handling library for `aiohttp`.

Implementation uses WIP version of Signals implemented by  @alexsdutton in [this](https://github.com/KeepSafe/aiohttp/issues/401) PR.

Currently all CORS handling logic is implemented, but tested only superficially.

While more complete tests and documentation will be committed later, right now I interested in feedback about API.
[README.rst](https://github.com/rutsky/aiohttp_cors/blob/initial_implementation/README.rst) has Usage section with examples of the current version of the API.

This is a part of https://github.com/KeepSafe/aiohttp/issues/516 fix.

### CODE REVIEW

**Comment by asvetlov** [comment]
Very exciting PR.
Looks pretty good.
I suggest merging as-is.
Let's discuss next changes after merge.
Say, I doubt using types in annotations make sense.
They are neither checked in runtime as I see nor pep 484 compatible.

**Comment by rutsky** [comment]
Let me fix starting of tests on Travis/Appveyor, and I will merge this PR.

**Comment by rutsky** [comment]
Ok, at least on Travis tests are being run (though not passing yet) - merging.

There is a lot of work to be done, but it's mostly infrastructure: tests, documentation, etc.

I will open appropriate pull requests.

**Comment by asvetlov** [comment]
Thanks

**Pull request merged**
